---
- name: Ensure SSH is running and enabled
  systemd:
    name: sshd
    state: started
    enabled: yes
  tags:
    - security
    - ssh

- name: Configure SSH security settings
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin {{ "yes" if allow_root_login else "no" }}' }
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
    - { regexp: '^#?Port', line: 'Port {{ ssh_port }}' }
  notify: restart sshd
  tags:
    - security
    - ssh

- name: Install security packages
  yum:
    name:
      - fail2ban
      - aide
    state: present
  tags:
    - security
    - packages

- name: Configure fail2ban for SSH protection
  copy:
    content: |
      [sshd]
      enabled = true
      port = {{ ssh_port }}
      filter = sshd
      logpath = /var/log/secure
      maxretry = 3
      bantime = 3600
      findtime = 600
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  tags:
    - security
    - fail2ban

- name: Start and enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes
  tags:
    - security
    - services

- name: Set up automatic security updates
  cron:
    name: "Security updates"
    minute: "0"
    hour: "2"
    job: "yum update -y --security"
    user: root
  tags:
    - security
    - updates

- name: Configure firewall if enabled
  block:
    - name: Install firewalld
      yum:
        name: firewalld
        state: present

    - name: Start and enable firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow SSH through firewall
      firewalld:
        service: ssh
        permanent: yes
        state: enabled
        immediate: yes

    - name: Allow HTTP through firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Allow HTTPS through firewall
      firewalld:
        service: https
        permanent: yes
        state: enabled
        immediate: yes
  when: enable_firewall
  tags:
    - security
    - firewall

- name: Disable IPv6 if requested
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
  when: disable_ipv6
  tags:
    - security
    - ipv6

- name: Set kernel security parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { name: 'net.ipv4.ip_forward', value: '0' }
    - { name: 'net.ipv4.conf.all.send_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.send_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.accept_redirects', value: '0' }
    - { name: 'net.ipv4.conf.all.secure_redirects', value: '0' }
    - { name: 'net.ipv4.conf.default.secure_redirects', value: '0' }
  tags:
    - security
    - kernel

- name: Log security setup completion
  lineinfile:
    path: /var/log/application.log
    line: "{{ ansible_date_time.iso8601 }}: Security baseline applied via Ansible - SSH Port: {{ ssh_port }}, Firewall: {{ enable_firewall }}"
  tags:
    - logging
